# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h3W4keoIHr_wYAQ-wenDYtrR6AimMD4R
"""

def mod_div(fun):
    def inner(x,y):
        if x < y:
            x, y = y, x
        fun(x,y)
    return inner

@mod_div
def div (x, y):
    print( x / y )
div(2,4)

