# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h3W4keoIHr_wYAQ-wenDYtrR6AimMD4R
"""

import random 
import string
ch=list(string.ascii_letters + string.digits)
OTP = ""
for i in range(6):
    OTP += random.choice(ch)
print (OTP)

