# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h3W4keoIHr_wYAQ-wenDYtrR6AimMD4R
"""

from collections import Counter
s= input("enter string: ")
print(Counter(s))

